// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVmHtQFWH5OO_-tT93XXyFdscMI_TnKfA',
    appId: '1:999184171602:web:d5e330783025d7e198958b',
    messagingSenderId: '999184171602',
    projectId: 'loveydovey-c5644',
    authDomain: 'loveydovey-c5644.firebaseapp.com',
    storageBucket: 'loveydovey-c5644.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_1_QTcvyrbtrz-gH2yATDejsSxq3BcB0',
    appId: '1:999184171602:android:a93d4d6644bade5498958b',
    messagingSenderId: '999184171602',
    projectId: 'loveydovey-c5644',
    storageBucket: 'loveydovey-c5644.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG_ra8y9fArD97wAXrJTti9E2FDGoGkTM',
    appId: '1:999184171602:ios:d98a935299513d9098958b',
    messagingSenderId: '999184171602',
    projectId: 'loveydovey-c5644',
    storageBucket: 'loveydovey-c5644.firebasestorage.app',
    iosBundleId: 'com.example.loveyDovey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG_ra8y9fArD97wAXrJTti9E2FDGoGkTM',
    appId: '1:999184171602:ios:d98a935299513d9098958b',
    messagingSenderId: '999184171602',
    projectId: 'loveydovey-c5644',
    storageBucket: 'loveydovey-c5644.firebasestorage.app',
    iosBundleId: 'com.example.loveyDovey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVmHtQFWH5OO_-tT93XXyFdscMI_TnKfA',
    appId: '1:999184171602:web:8a18881cd200468f98958b',
    messagingSenderId: '999184171602',
    projectId: 'loveydovey-c5644',
    authDomain: 'loveydovey-c5644.firebaseapp.com',
    storageBucket: 'loveydovey-c5644.firebasestorage.app',
  );
}
