import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:lovey_dovey/auth/auth_gate.dart';
import 'firebase_options.dart'; // This file was generated by flutterfire_cli

// We will create this file in the next step
// import 'package:lovey_dovey/screens/dashboard_screen.dart'; 

void main() async {
  // Ensure that Flutter bindings are initialized before calling Firebase
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Firebase using the generated options file
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'LoveyDovey',
      theme: ThemeData(
        primarySwatch: Colors.pink,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      // For now, we go straight to the dashboard. Later, we'll add logic
      // to check if the user is logged in.
      // Set AuthGate as the home widget
      home: AuthGate(), 
    );
  }
}